site_name: LimbLab
site_url: https://mydomain.org/mysite

theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: orange
    
  features:
    - navigation.instant

  logo: assets/logo.png

copyright: Copyright &copy; 2024 Sharpe Lab
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://fosstodon.org/@squidfunk
      name: Github Repository

nav:
  - LimbLab: index.md
  - User Guide: 
    - Volume Cleaning: userGuide/volume.md
    - Extract the Limb Surface: userGuide/surface.md
    - Limb Staging: userGuide/staging.md
    - Aligment to reference: userGuide/align.md
    - Visualitzation:
      - Gene Pattern Isosurfaces: userGuide/vis/isosurfaces.md
      - Dynamic Slab: userGuide/vis/slab.md
    - Customization: userGuide/style.md
  - Tutorials:
    - Sox9 & BMP2: tutorials/sox9_bmp2.md
    - Hoxa11: tutorials/hoxa11.md
  - Help and Requests: help.md
  - Roadmap: releases.md
  - Contribute: contribute.md
  - Alternatives: alternatives.md
  - Changelog: releases.md
