# pyright: reportOptionalMemberAccess=false
# pyright: ignore[reportAttributeAccessIssue]

from pathlib import Path
from types import SimpleNamespace
from typing import Any

import vtkmodules
from components.terminal_paper import TerminalPaperWidget
from config import *
from controllers.align_controller import AlignController
from controllers.clean_controller import CleanController
from controllers.stage_controller import StageController
from controllers.surface_controller import SurfaceController
from limblab.database.crud import (
    init_db,
)
from limblab.database.navigation import (
    seed_reference_limbs,
)
from limblab.design import theme
from limblab.utils import generate_kwargs
from mixin.NavigationMixin import NavigationMixin
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import (
    QApplication,
    QComboBox,
    QDialog,
    QDoubleSpinBox,
    QFrame,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QMainWindow,
    QMessageBox,
    QStatusBar,
    QToolButton,
    QTreeWidget,
    QTreeWidgetItem,
    QVBoxLayout,
    QWidget,
)
from utils import create_back_button, create_label, create_styled_button
from vedo import Mesh, Plotter
from vtkmodules.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor

vtkmodules.qt.QVTKRWIBase = "QGLWidget"



from controllers.navigate_controller import NavigationController
from controllers.visualization_controller import VisualizationController
from menu_utils import MenuUtils
from new_experiment_page_utils import NewExperimentPage
from database_gui_utils import DatabaseGUI
from visualization_page_utils import VisualizationPage


class MainWindow(QMainWindow, NavigationMixin, MenuUtils, NewExperimentPage, DatabaseGUI, VisualizationPage):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("LimbLab")
        self.setStyleSheet(f"QMainWindow, QWidget {{ background-color: {theme('palette.background', '#141414')}; color: {theme('palette.textPrimary', '#FFFFFF')}; }}")
        self.setStatusBar(QStatusBar(self))

        self.workflow_checkpoints = {
    "Clean": False,
    "Surface": False,
    "Stage": False,
    "Align": False,
    "Visualize": False # TODO: Think about this.
}

        ##########
        # DATABASE
        self.db_path = Path("experiments.db")

        self.experiment = None
        self.experiment_storage_folder = None
        self.uploaded_dapi_channel = False
        self.uploaded_gene_channel = {}
        self.current_channel = None
        self.workflow_checkpoints = {step: False for step in self.workflow_checkpoints}

        seed_reference_limbs(self.db_path)
                #called just once in the inizialization of hte app!
                #init_db is called in show_user_expoeriment page
        init_db(self.db_path)  # Creates empty database with schema only
    
        ############
        # NAMESPACES
        self.ui = SimpleNamespace()
        self.viewer = SimpleNamespace()
       

        self.experiments = []
        self.experiment_names = {}
        self.pipeline_log = []
        self.param_values = {}
        
        self.active_viz_sections = []


        # Navigation
        self.navigation_stack = []
        self.current_screen = None

        self.action_bar = None

        self.current_channel = None #this is first defined and generated by clean action
       
        # ---- Workflow state ----
        # Tracks whether the required action for each step of the
        # Viz -> Clean -> Surface -> Stage -> Align pipeline has been
        # completed. This drives both forward-navigation guards (can't
        # jump ahead without finishing the current step) and back
        # navigation warnings (you're about to lose unsaved progress).

        #standard workflow state for any experiment
        self.workflow_checkpoints = {
            "Clean": False,
            "Surface": False,
            "Stage": False,
            "Align": False,
            "Visualize": False # TODO: Think about this.
        }

        self.uploaded_dapi_channel = False
        self.uploaded_gene_channel = {}
        self.GENE_CHANNEL_TYPES = ['HOXA11', 'HOXA13', 'SOX9']#will be able to add other types of genes, user accepted gene argument name


        self.surface = SurfaceController(self)
        self.clean = CleanController(self)
        self.align = AlignController(self)
        self.stage = StageController(self) 
        self.visualizer = VisualizationController(self)

        self.navigation = NavigationController(self)
        self.navigation._build_permanent_chrome()

        # self.navigate_to(lambda:self.align.show(experiment))
        self.navigation.navigate_to(self.show_home)

    # ------------------------------------------------------------------
    # Menu Building Methods
    # ------------------------------------------------------------------


    # ------------------------------------------------------------------
    # Shared workflow-screen layout
    #
    # Every step of the pipeline (Viz, Clean, Surface, Stage, Align)
    # uses the exact same shell:
    #   - top row: Back button | Left menu | ...stretch... | Next-step button
    #   - the live 3D viewer
    #   - an optional per-step action bar just below the viewer
    #   - the same right-hand side panel (Visualizer / Pipeline / params)
    # This is what keeps the layout visually identical as the user moves
    # through the pipeline.
    # ------------------------------------------------------------------
    

    # NOTE: Laura build this. So if actually works for her. 
    def _build_workflow_container(
        self,
        experiment,
        next_label=None,
        next_callback=None,
        back_guard=None,
        action_widget=None,
        current_step=None,
    ):

        """Construct the standard workflow container used by pipeline screens.

        Layout (left -> right):
          - left: top row, 3D viewer, optional per-step action bar
          - right: side panel (visu_dalizer / pipeline / params)

        Parameters mirror what controllers pass in: next button label/callback,
        back guard callable, and an optional widget to show under the viewer.
        """

        self._active_back_guard = back_guard

        container = QWidget()
        h_layout = QHBoxLayout(container)
        h_layout.setContentsMargins(0, 0, 0, 0)
        h_layout.setSpacing(12)

        # --- Left: viewer + top row + action bar ---
        left = QWidget()
        left_layout = QVBoxLayout(left)
        left_layout.setContentsMargins(0, 0, 0, 0)
        left_layout.setSpacing(6)

        # Top row (Back / menu / Next)


        # Create a fresh VTK viewer widget for this container.
        # Reusing a previously-created QVTKRenderWindowInteractor can lead
        # to "wrapped C/C++ object has been deleted" errors when Qt
        # has already destroyed the old widget. Always instantiate a new
        # widget here and overwrite any previous references.
        try:
            self.frame = QFrame()
            self.vtkWidget = QVTKRenderWindowInteractor(self.frame)
            # create a Plotter for convenience (may be re-used by controllers)
            try:
                self.plt = Plotter(qt_widget=self.vtkWidget)
            except Exception:
                self.plt = None
        except Exception:
            # Fallback: lightweight placeholder
            self.vtkWidget = QWidget()

        # Keep both attribute names used elsewhere compatible
        self.vtk_widget = getattr(self, "vtkWidget")

        # Add the viewer to the layout
        left_layout.addWidget(self.vtkWidget, stretch=1)

        # Optional per-step action bar below the viewer
        if action_widget is not None:
            left_layout.addWidget(action_widget)

        h_layout.addWidget(left, stretch=3)

        # --- Right: side panel ---
        side = self._build_side_panel(experiment)
        
        h_layout.addWidget(side, stretch=1)

        return container

    
    # ------------------------------------------------------------------
    # Screen Methods
    # ------------------------------------------------------------------
    def show_home(self):
        self.action_bar.setVisible(False)

        topbar = self._build_home_topbar()

        left_panel = QWidget()
        get_started_btn = create_styled_button(
            "Get Started",
            size=50
        )
        get_started_btn.clicked.connect(
            lambda: self.navigation.navigate_to(self.show_lobby)
        )

        label_main = QLabel("LimbLab")
        try:
            hero_size = int(theme("typography.fontSizeHero", 100))
        except Exception:
            hero_size = 100
        fnt = label_main.font()
        fnt.setPointSize(hero_size)
        fnt.setBold(True)
        label_main.setFont(fnt)

        sublabel_main = create_label(
            "Analyze your 3D limb data with unprecedented ease.",
            f"color: {theme('palette.textSecondary', '#A0A0A0')}; font-size: {theme('typography.fontSizeLarge', 18)}px;",
        )

        left_layout = QVBoxLayout(left_panel)
        left_layout.addStretch(1)
        left_layout.addWidget(label_main, alignment=Qt.AlignmentFlag.AlignHCenter)
        left_layout.addWidget(sublabel_main, alignment=Qt.AlignmentFlag.AlignHCenter)
        left_layout.addSpacing(12)
        left_layout.addWidget(get_started_btn, alignment=Qt.AlignmentFlag.AlignHCenter)


        paper = TerminalPaperWidget(
            text=(
                "<- ->    use arrows to reduce/increase opacity\n"
                "x        toggle mesh visibility\n"
                "w        toggle wireframe/surface style\n"
                "l        toggle surface edges visibility\n"
                "1-3      cycle surface color\n"
                "k        cycle available lighting styles\n"
                "r        reset camera position\n"
                "shift    pan\n"
                "ctl/cmd  rotate over an axis"
            ),
            parent=self,
        )
        left_layout.addWidget(paper, alignment=Qt.AlignmentFlag.AlignHCenter)
        left_layout.addSpacing(8)
        left_layout.addStretch(2)
        left_layout.setContentsMargins(40, 0, 40, 0)

        self.frame = QFrame()
        self.vtkWidget = QVTKRenderWindowInteractor(self.frame)
        self.vtk_widget = self.vtkWidget

        self.limb_home = Mesh("Limb-rec_281.vtk").c(theme("limblab.surface"))
        
        params: dict[str, Any] = dict(bg = theme("palette.background"))
        kwargs = generate_kwargs(params=params, renderer='pyqt', outside_class=self)
        
        self.plt = Plotter(**kwargs)

        # Create vedo renderer and add objects and callbacks
        
        container = QWidget()
        container.setStyleSheet(f"background-color: {theme('palette.background', '#141414')};")
        outer_layout = QVBoxLayout(container)
        outer_layout.setContentsMargins(0, 0, 0, 0)
        outer_layout.setSpacing(0)
        outer_layout.addWidget(topbar)

        body = QWidget()
        layout = QHBoxLayout(body)
        layout.addWidget(left_panel, stretch=3)
        layout.addWidget(self.vtkWidget, stretch=2)
        outer_layout.addWidget(body, stretch=1)

        self.setCentralWidget(container)  
        self.plt.show(self.limb_home)


    def create_new_experiment_page(self):
        self.experiment = None
        self.experiment_storage_folder = None
        self.uploaded_dapi_channel = False
        self.uploaded_gene_channel = {}
        self.current_channel = None
        self.workflow_checkpoints = {step: False for step in self.workflow_checkpoints}

        top_row = QHBoxLayout()
        top_row.addWidget(create_back_button(self.navigation.go_back_using_arrow_btn))
        top_row.addWidget(self.create_left_button())
        top_row.addStretch()

        # ---- Track uploaded channel state (used by the status label below) ----
    
        # ---- Shared card style ----
        card_style = f"""
            QGroupBox {{
                color: {theme('palette.textPrimary', '#FFFFFF')};
                font-size: {theme('typography.fontSizeLabel', 15)}px;
                font-weight: 600;
                background-color: {theme('palette.surface', '#232323')};
                border: 1px solid {theme('palette.border', '#3A3A3A')};
                border-radius: 12px;
                margin-top: 14px;
                padding: 16px;
            }}
            QGroupBox::title {{
                subcontrol-origin: margin;
                left: 14px;
                top: -2px;
                padding: 0 8px;
            }}
            QLabel {{
                color: {theme('palette.textPrimary', '#FFFFFF')};
                font-size: {theme('typography.fontSizeBody', 13)}px;
                font-weight: 400;
            }}
            QComboBox, QDoubleSpinBox {{
                background-color: {theme('palette.surfaceAlt', '#2C2C2C')};
                color: {theme('palette.textPrimary', '#FFFFFF')};
                border: 1px solid {theme('palette.border', '#3A3A3A')};
                border-radius: 6px;
                padding: 4px 8px;
                min-height: 24px;
            }}
            QComboBox:hover, QDoubleSpinBox:hover {{
                border: 1px solid {theme('palette.primary', '#0D7C66')};
            }}
        """

        # ---- Limb Info ----
        limb_info_group = QGroupBox("Limb Info")
        limb_info_group.setStyleSheet(card_style)
        limb_info_layout = QVBoxLayout(limb_info_group)
        limb_info_layout.setSpacing(14)
        limb_info_layout.setContentsMargins(18, 24, 18, 18)

        side_layout = QHBoxLayout()
        side_layout.setSpacing(10)
        side_label = QLabel("Limb Side")
        side_label.setFixedWidth(90)
        self.side_combo = QComboBox()
        self.side_combo.addItems(["L", "R"])
        self.side_combo.setCurrentIndex(0)
        side_layout.addWidget(side_label)
        side_layout.addWidget(self.side_combo)
        limb_info_layout.addLayout(side_layout)

        position_layout = QHBoxLayout()
        position_layout.setSpacing(10)
        position_label = QLabel("Position")
        position_label.setFixedWidth(90)
        self.position_combo = QComboBox()
        self.position_combo.addItems(["F", "H"])
        self.position_combo.setCurrentIndex(0)
        position_layout.addWidget(position_label)
        position_layout.addWidget(self.position_combo)
        limb_info_layout.addLayout(position_layout)

        # Spacing (nested card, slightly recessed look)
        spacing_group = QGroupBox("Spacing")
        spacing_group.setStyleSheet(card_style + f"""
            QGroupBox {{
                background-color: {theme('palette.surfaceAlt', '#1D1D1D')};
            }}
        """)
        spacing_layout = QVBoxLayout(spacing_group)
        spacing_layout.setSpacing(8)
        spacing_layout.setContentsMargins(18, 22, 18, 16)

        for axis, default in (("X", 0.65), ("Y", 0.65), ("Z", 2.0)):
            axis_layout = QHBoxLayout()
            axis_layout.setSpacing(10)
            axis_label = QLabel(axis)
            axis_label.setFixedWidth(20)
            axis_label.setStyleSheet(f"font-weight: 600; color: {theme('palette.textSecondary', '#AAAAAA')};")
            spin = QDoubleSpinBox()
            spin.setRange(0.01, 10.0)
            spin.setSingleStep(0.01)
            spin.setValue(default)
            spin.setDecimals(2)
            axis_layout.addWidget(axis_label)
            axis_layout.addWidget(spin)
            spacing_layout.addLayout(axis_layout)
            setattr(self, f"{axis.lower()}_spin", spin)

        limb_info_layout.addWidget(spacing_group)

        self.limb_info = {
            'side': self.side_combo.currentText(),
            'position': self.position_combo.currentText(),
            'spacing': (self.x_spin.value(), self.y_spin.value(), self.z_spin.value()),
        }
        if not self.limb_info:
            return

        # ---- Upload group (DAPI + gene channels) ----
        upload_group = QGroupBox("Channels")
        upload_group.setStyleSheet(card_style)
        upload_layout = QVBoxLayout(upload_group)
        upload_layout.setSpacing(20)
        upload_layout.setContentsMargins(24, 28, 24, 24)

        self.label_upload_DAPI = create_label(
            "Upload a DAPI channel",
            f"color: {theme('palette.textPrimary', '#FFFFFF')}; "
            f"font-size: {theme('typography.fontSizeSubheading', 18)}px; font-weight: 600;"
        )
        self.button_upload_DAPI = create_styled_button(
            "Upload DAPI"
        )
        self.button_upload_DAPI.setMinimumWidth(140)
        self.button_upload_DAPI.setStyleSheet(
            self.button_upload_DAPI.styleSheet() + "border-radius: 8px; padding: 8px 16px; font-weight: 600;"
        )
        self.button_upload_DAPI.clicked.connect(lambda: self.create_new_experiment('DAPI'))

        self.label_upload_channel = create_label(
            "Upload a gene channel",
            f"color: {theme('palette.textPrimary', '#FFFFFF')}; "
            f"font-size: {theme('typography.fontSizeSubheading', 18)}px; font-weight: 600;"
        )
        self.button_upload_channel = create_styled_button(
            "Upload channel"
            # color=theme("palette.primary", "#0D7C66"),
            # hover_color=theme("palette.primaryHover", "#41B3A2"),
        )
        self.button_upload_channel.clicked.connect(lambda: self.create_new_experiment('other'))
        self.button_upload_channel.setMinimumWidth(140)
        self.button_upload_channel.setStyleSheet(
            self.button_upload_channel.styleSheet() + "border-radius: 8px; padding: 8px 16px; font-weight: 600;"
        )

        # ---- Status label ----
        self.channel_status_label = create_label(
            self._build_channel_status_text(),
            f"color: {theme('palette.textSecondary', '#CCCCCC')}; "
            f"font-size: {theme('typography.fontSizeBody', 13)}px; "
            f"padding: 10px 12px; background-color: {theme('palette.surfaceAlt', '#1D1D1D')}; "
            f"border-radius: 8px; border: 1px solid {theme('palette.border', '#3A3A3A')};"
        )
        self.channel_status_label.setWordWrap(True)

        dapi_col = QVBoxLayout()
        dapi_col.setSpacing(10)
        dapi_col.addWidget(self.label_upload_DAPI, alignment=Qt.AlignmentFlag.AlignHCenter)
        dapi_col.addWidget(self.button_upload_DAPI, alignment=Qt.AlignmentFlag.AlignHCenter)

        gene_col = QVBoxLayout()
        gene_col.setSpacing(10)
        gene_col.addWidget(self.label_upload_channel, alignment=Qt.AlignmentFlag.AlignHCenter)
        gene_col.addWidget(self.button_upload_channel, alignment=Qt.AlignmentFlag.AlignHCenter)

        upload_buttons_row = QHBoxLayout()
        upload_buttons_row.setSpacing(48)
        upload_buttons_row.addLayout(dapi_col)
        upload_buttons_row.addLayout(gene_col)

        upload_layout.addLayout(upload_buttons_row)
        upload_layout.addWidget(self.channel_status_label)

        left_column = QVBoxLayout()
        left_column.setSpacing(20)
        left_column.addWidget(limb_info_group)

        right_column = QVBoxLayout()
        right_column.setSpacing(20)
        right_column.addWidget(upload_group)

        buttons_row = QHBoxLayout()
        buttons_row.setSpacing(28)
        buttons_row.addLayout(left_column, stretch=1)
        buttons_row.addLayout(right_column, stretch=1)

        # ---- Output location (required before any upload) ----
        output_group = QGroupBox("Output Location")
        output_group.setStyleSheet(card_style)
        output_layout = QVBoxLayout(output_group)
        output_layout.setSpacing(10)
        output_layout.setContentsMargins(18, 22, 18, 16)

        output_layout.addWidget(create_label(
            "Choose where to store files generated for this "
            "experiment (.vti cleaned volumes, .vtk surface, transformation matrix, and "
            "a copy of the database).\n"
            "A folder named after the experiment id will be created at the chosen location.",
            f"color: {theme('palette.textSecondary', '#AAAAAA')}; font-size: {theme('typography.fontSizeBody', 12)}px;"
        ))

        self.experiment_storage_folder = None  # reset each time this page is opened

        output_row = QHBoxLayout()
        self.output_folder_label = create_label(
            "No directory set",
            f"color: {theme('palette.textPrimary', '#FFFFFF')}; font-style: italic;"
        )
        choose_output_btn = create_styled_button(
            "Choose Directory"
        )
        choose_output_btn.clicked.connect(self._choose_output_parent_dir)
        output_row.addWidget(self.output_folder_label, stretch=1)
        output_row.addWidget(choose_output_btn)
        output_layout.addLayout(output_row)


        # ---- Visualize / Next button ----
        self.button_visualize = create_styled_button(
            "Visualize \u2192",
        )
        self.button_visualize.setMinimumWidth(160)
        self.button_visualize.setMinimumHeight(40)
        self.button_visualize.setStyleSheet(
            self.button_visualize.styleSheet() +
            "border-radius: 8px; font-weight: 700; font-size: 15px; padding: 8px 20px;"
        )

        self.button_visualize.clicked.connect(
            lambda: self.navigation.navigate_to(lambda: self.visualizer.show_experiment(self.experiment))
            if self.uploaded_dapi_channel
            else QMessageBox.warning(self, 'Upload DAPI channel', 'To create any experiment, you need to upload a DAPI channel'))


        visualize_row = QHBoxLayout()
        visualize_row.addStretch()
        visualize_row.addWidget(self.button_visualize)

        container = QWidget()
        container.setStyleSheet(f"background-color: {theme('palette.background', '#181818')};")
        layout = QVBoxLayout(container)
        layout.setContentsMargins(28, 20, 28, 28)
        layout.setSpacing(16)
        layout.addLayout(top_row)
        layout.addWidget(output_group)
        layout.addStretch(1)
        layout.addLayout(buttons_row, stretch=0)
        layout.addStretch(2)
        layout.addLayout(visualize_row)
        self.setCentralWidget(container)


    def show_lobby(self):
        self.action_bar.setVisible(False)

        top_row = QHBoxLayout()
        top_row.addWidget(create_back_button(self.navigation.go_back_using_arrow_btn))
        top_row.addWidget(self.create_left_button())
        top_row.addStretch()

        # ---- Create New Experiment [UPLOAD] ----
        self.label_upload = create_label(
            "Create New Experiment", 
            f"color: {theme('palette.textPrimary', '#FFFFFF')}; font-size: {theme('typography.fontSizeHero', 40)}px;"
        )
        self.button_upload = create_styled_button("New Experiment",border_color = theme("palette.secondary", "#54278F"),
                                                  border_hover_color=theme("palette.secondaryHover", "#756BB1")
            
        )
        self.button_upload.clicked.connect(lambda: self.navigation.navigate_to(self.create_new_experiment_page))

        upload_desc = create_label(
            "Upload a TIF volume to start a new experiment.\n"
            "You can add more channels later.",
            f"color: {theme('palette.textSecondary', '#A0A0A0')}; font-size: {theme('typography.fontSizeBase', 14)}px; text-align: center;"
        )
        upload_desc.setAlignment(Qt.AlignmentFlag.AlignCenter)
        upload_desc.setWordWrap(True)

        
        # ---- Library Access [YOUR DATA] ----
        self.label_library = create_label("Access Limb Library", f"color: {theme('palette.textPrimary', '#FFFFFF')}; font-size: {theme('typography.fontSizeHero', 40)}px;")
        self.button_library = create_styled_button(
            "View Experiments"
        )
        self.button_library.clicked.connect(lambda: self.navigation.navigate_to(self.show_user_experiment_list))

        library_desc = create_label(
            "View and manage your existing experiments\n"
            "or load them for visualization.",
            f"color: {theme('palette.textSecondary', '#A0A0A0')}; font-size: {theme('typography.fontSizeBase', 14)}px; text-align: center;"
        )
        library_desc.setAlignment(Qt.AlignmentFlag.AlignCenter)
        library_desc.setWordWrap(True)

        # ---- Layout ----
        upload_column = QVBoxLayout()
        upload_column.addWidget(self.label_upload, alignment=Qt.AlignmentFlag.AlignHCenter)
        upload_column.addWidget(self.button_upload, alignment=Qt.AlignmentFlag.AlignHCenter)
        upload_column.addWidget(upload_desc, alignment=Qt.AlignmentFlag.AlignHCenter)

        library_column = QVBoxLayout()
        library_column.addWidget(self.label_library, alignment=Qt.AlignmentFlag.AlignHCenter)
        library_column.addWidget(self.button_library, alignment=Qt.AlignmentFlag.AlignHCenter)
        library_column.addWidget(library_desc, alignment=Qt.AlignmentFlag.AlignHCenter)

        buttons_row = QHBoxLayout()
        buttons_row.addLayout(upload_column)
        buttons_row.addSpacing(40)
        buttons_row.addLayout(library_column)

        container = QWidget()
        layout = QVBoxLayout(container)
        layout.addLayout(top_row)
        layout.addStretch(1)
        layout.addLayout(buttons_row, stretch=0)
        layout.addStretch(2)
        self.setCentralWidget(container)


    def show_user_experiment_list(self):
        self.action_bar.setVisible(False)
        self._load_experiments_from_db()

        top_row = QHBoxLayout()
        top_row.addWidget(create_back_button(self.navigation.go_back_using_arrow_btn))
        top_row.addWidget(self.create_left_button())
        top_row.addStretch()

        # Use a tree view for clear hierarchy: experiments -> channels
        tree = QTreeWidget()
        tree.setColumnCount(2)
        tree.setHeaderHidden(True)
        tree.setStyleSheet(f"background-color: {theme('palette.panel', '#2A2A2A')}; border-radius: {theme('shape.borderRadiusPanel', '12px')};")
        tree.setIndentation(20)

        for path in self.experiments:
            exp_obj = self.experiment_metadata.get(path)
            if exp_obj is None:
                continue

            # displayed_name = self.experiment_names.get(path, os.path.basename(path))
            channels = exp_obj.channels if hasattr(exp_obj, 'channels') else []

            parent = QTreeWidgetItem(tree)
            # store experiment id on the item
            parent.setData(0, Qt.ItemDataRole.UserRole, path)

            # Left column: name + meta
            name_widget = QWidget()
            name_layout = QHBoxLayout(name_widget)
            name_layout.setContentsMargins(8, 6, 8, 6)
            name_label = QLabel(exp_obj.displayed_name)
            name_label.setStyleSheet(f"color: {theme('palette.textPrimary', '#FFFFFF')}; font-size: {theme('typography.fontSizeLarge', 18)}px;")
            channel_info = QLabel(f"({len(channels)} channels)")
            channel_info.setStyleSheet(f"color: {theme('palette.textSecondary', '#A0A0A0')}; font-size: {theme('typography.fontSizeSmall', 12)}px;")
            name_layout.addWidget(name_label)
            name_layout.addSpacing(8)
            name_layout.addWidget(channel_info)
            name_layout.addStretch()
            tree.setItemWidget(parent, 0, name_widget)

            # Right column: action buttons for experiment
            # compact action buttons (icon-like) for readability
            act_widget = QWidget()
            act_layout = QHBoxLayout(act_widget)
            act_layout.setContentsMargins(4, 2, 4, 2)
            act_layout.setSpacing(6)

            def make_small_btn(text, bg, hover, callback, border=None):
                btn = QToolButton()
                btn.setText(text)
                btn.setCursor(Qt.CursorShape.PointingHandCursor)
                btn.setFixedSize(76, 28)
                btn.setToolTip(text)
                border_color = border or bg
                btn.setStyleSheet(f"""
                    QToolButton {{
                        background-color: {bg};
                        color: {theme('palette.textPrimary', '#FFFFFF')};
                        border: 1px solid {border_color};
                        border-radius: {theme('shape.borderRadiusSmall', '2px')};
                        font-size: 12px;
                        font-weight: {theme('typography.fontWeightBold', '600')};
                        padding: 0px 8px;
                    }}
                    QToolButton:hover {{
                        background-color: {hover};
                        border: 1px solid {hover};
                    }}
                    QToolButton:pressed {{
                        background-color: {border_color};
                    }}
                """)
                btn.clicked.connect(callback)
                return btn

            view_btn = make_small_btn(
                'View',
                theme('palette.buttonDark', '#3A3F42'),
                theme('palette.buttonDarkHover', '#4A5054'),
                lambda checked=False, p=path: self._view_experiment(p),
                border=theme('palette.primary', '#0D7C66'),
            )
            add_ch_btn = make_small_btn(
                '+Channel',
                theme('palette.buttonDark', '#3A3F42'),
                theme('palette.buttonDarkHover', '#4A5054'),
                lambda checked=False, p=path: self._add_channel_to_existing(p),
                border=theme('palette.secondary', '#54278F'),
            )
            del_btn = make_small_btn(
                'Delete',
                theme('palette.buttonDark', '#3A3F42'),
                theme('palette.buttonDarkHover', '#4A5054'),
                lambda checked=False, p=path, n=exp_obj.displayed_name: self._delete_experiment(p, n),
                border=theme('palette.error', '#D9534F'),
            )
            rename_btn = make_small_btn(
                'Rename',
                theme('palette.buttonDark', '#3A3F42'),
                theme('palette.buttonDarkHover', '#4A5054'),
                lambda checked=False, p=path: self._rename_experiment(p, exp_obj.experiment_id, exp_obj.displayed_name),
                border=theme('palette.accent', '#5FBF9F'),
            )

            act_layout.addWidget(view_btn)
            act_layout.addWidget(add_ch_btn)
            act_layout.addWidget(rename_btn)
            act_layout.addWidget(del_btn)
            tree.setItemWidget(parent, 1, act_widget)

            # Add channels as children
            for ch in channels:
                ch_name = ch.channel_name if hasattr(ch, 'channel_name') else ch.get('channel_name', '')
                ch_id = ch.id if hasattr(ch, 'id') else ch.get('id')
                child = QTreeWidgetItem(parent)
                # store channel info: tuple (experiment_id, channel_name)
                child.setData(0, Qt.ItemDataRole.UserRole, (path, ch_name, ch_id))
                ch_widget = QWidget()
                ch_layout = QHBoxLayout(ch_widget)
                ch_layout.setContentsMargins(8, 4, 8, 4)
                ch_label = QLabel(f"• {ch_name}")
                ch_label.setStyleSheet(f"color: {theme('palette.textSecondary', '#A0A0A0')}; font-size: {theme('typography.fontSizeBase', 13)}px;")
                ch_layout.addSpacing(8)
                ch_layout.addWidget(ch_label)
                ch_layout.addStretch()
                tree.setItemWidget(child, 0, ch_widget)

                ch_act = QWidget()
                ch_act_layout = QHBoxLayout(ch_act)
                ch_act_layout.setContentsMargins(4, 2, 4, 2)
                ch_act_layout.setSpacing(6)

                ch_del = QToolButton()
                ch_del.setText('Delete')
                ch_del.setFixedSize(70, 26)
                ch_del.setToolTip('Delete')
                ch_del.setStyleSheet(f"""
                    QToolButton {{
                        background-color: {theme('palette.buttonDark', '#3A3F42')};
                        color: {theme('palette.textPrimary', '#FFFFFF')};
                        border: 1px solid {theme('palette.error', '#D9534F')};
                        border-radius: {theme('shape.borderRadiusSmall', '2px')};
                        font-size: 12px;
                        padding: 0px 6px;
                    }}
                    QToolButton:hover {{
                        background-color: {theme('palette.error', '#D9534F')};
                        border: 1px solid {theme('palette.error', '#D9534F')};
                    }}
                """)
                ch_del.clicked.connect(lambda checked=False, p=path, c=ch_name, cid=ch_id: self._delete_channel(p, c, cid))
                ch_act_layout.addWidget(ch_del)
                tree.setItemWidget(child, 1, ch_act)

        # expose tree for other handlers (view button, bulk actions)
        self.experiments_tree = tree

        # improve readability: uniform row heights and column sizing
        tree.setUniformRowHeights(True)
        tree.setRootIsDecorated(True)
        tree.header().setStretchLastSection(False)
        tree.resizeColumnToContents(0)
        tree.setColumnWidth(1, 300)

        experiments_card = QWidget()
        experiments_layout = QVBoxLayout(experiments_card)
        experiments_layout.setContentsMargins(0, 0, 0, 0)
        experiments_layout.addWidget(tree)
        experiments_card.setMinimumHeight(250)

        self.add_btn = create_styled_button(
            '+ Add Experiment',
            border_color=theme('palette.secondary', '#54278F'),
            border_hover_color=theme('palette.secondaryHover', '#756BB1'),
        )
        
        self.refresh_btn = create_styled_button(
            '↻ Refresh'
            # color=theme('palette.accent', '#0D7C66'),
            # hover_color=theme('palette.primaryHover', '#41B3A2'),
        )

        self.add_btn.clicked.connect(lambda: self.navigation.navigate_to(self.create_new_experiment_page))
        #self.add_channel_btn.clicked.connect(self.addchannel_button_clicked)
        #self.view_btn.clicked.connect(self.viewexp_button_clicked)
        self.refresh_btn.clicked.connect(self._refresh_experiments)

        buttons_row = QVBoxLayout()
        buttons_row.setContentsMargins(0, 20, 0, 20)  # Add vertical padding

        # Add stretch before and after to center the group, but with big spacing
        buttons_row.addStretch(1)  # Big stretch on left
        buttons_row.addWidget(self.add_btn)
        buttons_row.addSpacing(10)
        buttons_row.addStretch(1)
        buttons_row.addWidget(self.refresh_btn)
        buttons_row.addStretch(1)

        # Assemble everything
        container = QWidget()
        main_layout = QVBoxLayout(container)
        main_layout.addLayout(top_row)
        main_layout.addWidget(experiments_card, stretch=1)

        # Add the buttons row with some spacing
        main_layout.addSpacing(10)
        main_layout.addLayout(buttons_row)
        main_layout.addStretch(1)  # Extra stretch at bottomadd.
        main_layout.setContentsMargins(30, 20, 30, 5)

        self.setCentralWidget(container)

    def _show_busy(self, message):
        self._busy_dialog = QDialog(self)
        self._busy_dialog.setWindowTitle("Please wait")
        self._busy_dialog.setModal(True)
        self._busy_dialog.setStyleSheet(f"background-color: {theme('palette.surface', '#1E1E1E')}; color: {theme('palette.textPrimary', '#FFFFFF')};")
        layout = QVBoxLayout(self._busy_dialog)
        layout.addWidget(create_label(message, f"color: {theme('palette.textPrimary', '#FFFFFF')}; font-size: {theme('typography.fontSizeBase', 14)}px;"))
        self._busy_dialog.setFixedSize(320, 100)
        self._busy_dialog.show()
        QApplication.processEvents()

    def _hide_busy(self):
        if getattr(self, "_busy_dialog", None) is not None:
            self._busy_dialog.close()
            self._busy_dialog = None


    
